// Yashfeen EMR Constants & Catalogs

export const DEFAULT_DOCTOR_INFO = {
  name: 'Dr. Umar Farooq',
  degree: 'DHMS (RMP) — Physician & Homoeopath',
  regNo: 'RHMP012245',
  clinicName: 'Yashfeen Homoeopathic Clinic',
  address: 'Yashfeen Homoeopathic Clinic, PK',
  phone: '+92 300 1234567',
  email: 'contact@yashfeen.com',
};

export const REMEDIES = [
  'Aconitum Napellus',
  'Allium Cepa',
  'Antimonium Tartaricum',
  'Apis Mellifica',
  'Arnica Montana',
  'Arsenicum Album',
  'Belladonna',
  'Bryonia Alba',
  'Calcarea Carbonica',
  'Calcarea Fluorica',
  'Calcarea Phosphorica',
  'Carbo Vegetabilis',
  'Causticum',
  'Chamomilla',
  'Cinchona Officinalis (China)',
  'Colocynthis',
  'Dulcamara',
  'Eupatorium Perfoliatum',
  'Ferrum Phosphoricum',
  'Gelsemium Sempervirens',
  'Hepar Sulphuris Calcareum',
  'Hypericum Perforatum',
  'Ignatia Amara',
  'Ipecacuanha',
  'Kali Bichromicum',
  'Kali Carbonicum',
  'Kali Phosphoricum',
  'Lachesis Muta',
  'Ledum Palustre',
  'Lycopodium Clavatum',
  'Magnesia Phosphorica',
  'Mercurius Solubilis',
  'Natrum Muriaticum',
  'Natrum Sulphuricum',
  'Nux Vomica',
  'Phosphorus',
  'Phytolacca Decandra',
  'Podophyllum Peltatum',
  'Pulsatilla Pratensis',
  'Rhus Toxicodendron',
  'Ruta Graveolens',
  'Sabadilla',
  'Sarsaparilla',
  'Secale Cornutum',
  'Sepia Officinalis',
  'Silicea (Silica)',
  'Spongia Tosta',
  'Staphysagria',
  'Sulphur',
  'Symphytum Officinale',
  'Thuja Occidentalis',
  'Urtica Urens',
  'Veratrum Album',
  'Zincum Metallicum',
];

export const POTENCIES = [
  'Q (Mother Tincture)',
  '6X',
  '12X',
  '30C',
  '200C',
  '1M',
  '10M',
  'CM',
  '0/1 LM',
  '0/2 LM',
  '0/3 LM',
  '0/4 LM',
  '0/5 LM',
  '0/6 LM',
  '0/12 LM',
  '0/18 LM',
  '0/24 LM',
  '0/30 LM',
];

export const VEHICLES = [
  'Pills Size 30',
  'Pills Size 40',
  'Liquid Drops',
  'Powder (Saccharum Lactis)',
  'Distilled Water',
  'Globules',
  'Tablets',
  'External Ointment',
];

export const DIET_PRECAUTIONS_PRESETS = [
  'No Raw Onion/Garlic',
  'No Mint/Coffee',
  'Take on empty stomach',
  '30 mins gap before/after food',
  'Avoid sour foods',
  'Avoid strong perfumes/smells',
  'Avoid aerated drinks',
  'Take with warm water',
];
